# database generated on 2024-08-08 06:00 GMT
!!omap
- /home/shakti-iitm/RCT/new-ctg/riscv-ctg/Zcmt/RV32/CMJALT_TEST1/cm.jalt-01.S:
    commit_id: '-'
    isa:
    - RV32I_Zca_Zcmt
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*I.*Zca.*Zcmt.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - cm.jalt
