# database generated on 2024-08-12 04:32 GMT
!!omap
- /home/shakti-iitm/RCT/new-ctg/riscv-ctg/Zcmt/RV64/CMJT_TEST2/cm.jt-01.S:
    commit_id: '-'
    isa:
    - RV64I_Zca_Zcmt
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*I.*Zca.*Zcmt.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - cm.jt
